context: ../../../../fpga/magic/grady18_N2_10x6/ctx.pkl
compiler: iverilog
design:
    name: bcd2bin
    sources:
        - ../../src/bcd2bin.v
constraints:
    io: io.partial
tests:
    basic:
        sources:
            - ../../src/bcd2bin_test_basic.v
