name: Install Icarus Verilog

description: |
  Use cached iverilog if possible.

runs:
  using: composite
  steps:
    - name: Cache iverilog
      id: cache-ivl
      uses: actions/cache@v2
      with:
        path: iverilog
        key: iverilog

    - name: Checkout iverilog
      uses: actions/checkout@v2
      if: ${{ ! steps.cache-ivl.outputs.cache-hit }}
      with:
        repository: steveicarus/iverilog
        path: iverilog

    - name: Compile iverilog
      if: ${{ ! steps.cache-ivl.outputs.cache-hit }}
      run: |
        sudo apt-get install gperf autoconf
        pushd iverilog
        sh autoconf.sh
        ./configure --prefix=${GITHUB_WORKSPACE}/local
        make -j8
        popd

    - name: Install iverilog
      run: |
        pushd iverilog
        make install
        popd
