context: ../../../../fpga/magic/grady18v2_N2_8x8_hier/ctx.pkl
compiler: iverilog
app:
    name: bcd2bin
    sources:
        - ../../src/bcd2bin.v
constraints:
    io: io.partial
tests:
    basic:
        sources:
            - ../../src/bcd2bin_test_basic.v
