context: ${PRGA_ROOT}/examples/fpga/magic/hardpico/ctx.pkl
compiler: vcs
design:
    name: picosoc
    sources:
        - ../../src/simpleuart.v
        - ../../src/spimemio.v
        - ../../src/picosoc.v
constraints:
    io: io.partial
