context: ../../../../fpga/frame/grady18_N4_rom2K_8x8/ctx.pkl
compiler: iverilog
app:
  name: romtest
  sources: 
    - ../../src/romtest.v
  includes:
    - ../../src/include
constraints:
  io: io.partial
tests:
  romtest_test:
    sources:
      - ../../src/romtest_test.v
