# quickcheck
name: quickcheck

# Controls when the action will run. 
on:

  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Install PRGA
  install:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4
        with:
          ref: dev

      # Install dependencies
      - name: Install dependencies
        run: sudo apt-get install tcl8.6-dev autoconf
          
      # Install PRGA
      - name: Install PRGA
        run: bash envscr/install

      # Checkout iverilog
      - uses: actions/checkout@v2.3.4
        with:
          repository: steveicarus/iverilog
          path: iverilog

      # compile and install iverilog
      - name: Install iverilog
        run: pushd iverilog && sh autoconf.sh --prefix=${GITHUB_WORKSPACE}/local && ./configure && make && make install

  # Run test
